---
- hosts: 172.31.7.229
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install java
    apt:
      name: apache2
      state: present

  - name: i want to create a folder
    file:
      path: /home/mohit/myfolder
      state: directory

  - name: copy a file into node side
    copy:
      src: mytextfile
      dest: /home/mohit/myfolder

  - name: download any internet file
    get_url:
      url: https://updates.jenkins.io/download/war/2.508/jenkins.war
      dest: /home/mohit/myfolder
      force_basic_auth: yes


  - name: i want to copy index file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startwebserver

  handlers:
  - name: startwebserver
    service:
      name: apache2
      state: started